import 'package:flutter_application_1/model/product.dart';

class MyProduct {
  static List<Product> allProducts = [
    Product(
        id: 1,
        name: 'Nike Air Max 200',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Adidas',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Puma',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Rebook',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Lacoste',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
    Product(
        id: 1,
        name: 'Jackets1',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Roger Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Blazer Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Blazer Jackets4',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Teal Style Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
    Product(
        id: 1,
        name: 'Nike Air Max 200',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Adidas',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Puma',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Rebook',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Lacoste',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
    Product(
        id: 1,
        name: 'Jackets1',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Roger Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Blazer Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Blazer Jackets4',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Teal Style Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
  ];

  static List<Product> snekaersList = [
    Product(
        id: 1,
        name: 'Nike Air Max 200',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Adidas',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Puma',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Rebook',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Lacoste',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
    Product(
        id: 1,
        name: 'Nike Air Max 200',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Adidas',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Puma',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Rebook',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Lacoste',
        category: 'Trending Now',
        image: 'assets/sneakers_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
  ];

  static List<Product> jacketsList = [
    Product(
        id: 1,
        name: 'Jackets1',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Roger Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Blazer Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Blazer Jackets4',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Teal Style Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
    Product(
        id: 1,
        name: 'Jackets1',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/1.png',
        description: 'description',
        price: 180.00,
        quantity: 1),
    Product(
        id: 2,
        name: 'Roger Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/2.png',
        description: 'description',
        price: 280.00,
        quantity: 1),
    Product(
        id: 3,
        name: 'Blazer Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/3.png',
        description: 'description',
        price: 380.00,
        quantity: 1),
    Product(
        id: 4,
        name: 'Blazer Jackets4',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/4.png',
        description: 'description',
        price: 190.00,
        quantity: 1),
    Product(
        id: 5,
        name: 'Teal Style Jackets',
        category: 'Trending Now',
        image: 'assets/jacket_pictures/5.png',
        description: 'description',
        price: 350.00,
        quantity: 1),
  ];
}
